### ISSUE TITLE
[compiling] error

### ISSUE THREAD

**Issue by pagetronic** [state-of-the-art/Handy3DScanner#79]
### Issue description:
Issue when compiling on Ubuntu 20.10

### Environment:
Ubuntu

`[133/135] Building CXX object CMakeFiles/handy3dscanner.dir/src/camera/pointcloud.cpp.o
FAILED: CMakeFiles/handy3dscanner.dir/src/camera/pointcloud.cpp.o 
/usr/bin/c++  -DPROJECT_VERSION=\"0.5.1\" -DQT_3DCORE_LIB -DQT_3DEXTRAS_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DQUICKEXTRAS_LIB -DQT_3DQUICK_LIB -DQT_3DRENDER_LIB -DQT_CORE_LIB -DQT_DISABLE_DEPRECATED_BEFORE=0x060000 -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_NO_FOREACH -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICK_LIB -DQT_SENSORS_LIB -I. -I../../ -Ihandy3dscanner_autogen/include -I../../lib/pcl -I../../lib/src/librealsense-2.20.0/include -I../../lib/src/librealsense-2.20.0/third-party -I../../lib/src/draco-1.3.5/src -Ilib/draco/draco -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtQmlModels -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtSensors -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DCore -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DRender -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DInput -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DQuick -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DLogic -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DQuickExtras -isystem /usr/include/x86_64-linux-gnu/qt5/Qt3DExtras -std=c++11  -O3 -DNDEBUG   -fPIC -std=gnu++11 -MD -MT CMakeFiles/handy3dscanner.dir/src/camera/pointcloud.cpp.o -MF CMakeFiles/handy3dscanner.dir/src/camera/pointcloud.cpp.o.d -o CMakeFiles/handy3dscanner.dir/src/camera/pointcloud.cpp.o -c ../../src/camera/pointcloud.cpp
../../src/camera/pointcloud.cpp: In constructor 'PointCloud::PointCloud(QObject*)':
../../src/camera/pointcloud.cpp:40:62: warning: 'Qt3DRender::QBuffer::QBuffer(Qt3DRender::QBuffer::BufferType, Qt3DCore::QNode*)' is deprecated [-Wdeprecated-declarations]
   40 |     vertex_buffer(new QBuffer(QBuffer::VertexBuffer, geometry)),
      |                                                              ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QBuffer:1,
                 from ../../src/camera/pointcloud.cpp:16:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qbuffer.h:99:28: note: declared here
   99 |     QT_DEPRECATED explicit QBuffer(BufferType ty, Qt3DCore::QNode *parent = nullptr);
      |                            ^~~~~~~
../../src/camera/pointcloud.cpp:43:61: warning: 'Qt3DRender::QBuffer::QBuffer(Qt3DRender::QBuffer::BufferType, Qt3DCore::QNode*)' is deprecated [-Wdeprecated-declarations]
   43 |     color_buffer(new QBuffer(QBuffer::VertexBuffer, geometry)),
      |                                                             ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QBuffer:1,
                 from ../../src/camera/pointcloud.cpp:16:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qbuffer.h:99:28: note: declared here
   99 |     QT_DEPRECATED explicit QBuffer(BufferType ty, Qt3DCore::QNode *parent = nullptr);
      |                            ^~~~~~~
../../src/camera/pointcloud.cpp:46:60: warning: 'Qt3DRender::QBuffer::QBuffer(Qt3DRender::QBuffer::BufferType, Qt3DCore::QNode*)' is deprecated [-Wdeprecated-declarations]
   46 |     index_buffer(new QBuffer(QBuffer::IndexBuffer, geometry)),
      |                                                            ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QBuffer:1,
                 from ../../src/camera/pointcloud.cpp:16:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qbuffer.h:99:28: note: declared here
   99 |     QT_DEPRECATED explicit QBuffer(BufferType ty, Qt3DCore::QNode *parent = nullptr);
      |                            ^~~~~~~
../../src/camera/pointcloud.cpp:49:76: error: 'QLatin1Literal' was not declared in this scope; did you mean 'QStringLiteral'?
   49 |     index_enabled(Settings::I()->val("UI.Edit.display_mode").toString() != QLatin1Literal("POINTS")),
      |                                                                            ^~~~~~~~~~~~~~
      |                                                                            QStringLiteral
../../src/camera/pointcloud.cpp:50:63: warning: 'Qt3DRender::QBuffer::QBuffer(Qt3DRender::QBuffer::BufferType, Qt3DCore::QNode*)' is deprecated [-Wdeprecated-declarations]
   50 |     options_buffer(new QBuffer(QBuffer::VertexBuffer, geometry)),
      |                                                               ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QBuffer:1,
                 from ../../src/camera/pointcloud.cpp:16:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qbuffer.h:99:28: note: declared here
   99 |     QT_DEPRECATED explicit QBuffer(BufferType ty, Qt3DCore::QNode *parent = nullptr);
      |                            ^~~~~~~
../../src/camera/pointcloud.cpp: In member function 'void PointCloud::setVertexAttribute()':
../../src/camera/pointcloud.cpp:505:89: warning: 'void Qt3DRender::QAttribute::setDataType(Qt3DRender::QAttribute::VertexBaseType)' is deprecated [-Wdeprecated-declarations]
  505 |     vertex_attribute->setDataType(static_cast<QAttribute::VertexBaseType>(vertex_format));
      |                                                                                         ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QAttribute:1,
                 from ../../src/camera/pointcloud.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qattribute.h:130:24: note: declared here
  130 |     QT_DEPRECATED void setDataType(VertexBaseType type);
      |                        ^~~~~~~~~~~
../../src/camera/pointcloud.cpp:506:36: warning: 'void Qt3DRender::QAttribute::setDataSize(uint)' is deprecated [-Wdeprecated-declarations]
  506 |     vertex_attribute->setDataSize(3);
      |                                    ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QAttribute:1,
                 from ../../src/camera/pointcloud.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qattribute.h:131:24: note: declared here
  131 |     QT_DEPRECATED void setDataSize(uint size);
      |                        ^~~~~~~~~~~
../../src/camera/pointcloud.cpp: In member function 'void PointCloud::setColorAttribute()':
../../src/camera/pointcloud.cpp:522:87: warning: 'void Qt3DRender::QAttribute::setDataType(Qt3DRender::QAttribute::VertexBaseType)' is deprecated [-Wdeprecated-declarations]
  522 |     color_attribute->setDataType(static_cast<QAttribute::VertexBaseType>(color_format));
      |                                                                                       ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QAttribute:1,
                 from ../../src/camera/pointcloud.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qattribute.h:130:24: note: declared here
  130 |     QT_DEPRECATED void setDataType(VertexBaseType type);
      |                        ^~~~~~~~~~~
../../src/camera/pointcloud.cpp:523:35: warning: 'void Qt3DRender::QAttribute::setDataSize(uint)' is deprecated [-Wdeprecated-declarations]
  523 |     color_attribute->setDataSize(4);
      |                                   ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QAttribute:1,
                 from ../../src/camera/pointcloud.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qattribute.h:131:24: note: declared here
  131 |     QT_DEPRECATED void setDataSize(uint size);
      |                        ^~~~~~~~~~~
../../src/camera/pointcloud.cpp: In member function 'void PointCloud::setIndexAttribute()':
../../src/camera/pointcloud.cpp:539:57: warning: 'void Qt3DRender::QAttribute::setDataType(Qt3DRender::QAttribute::VertexBaseType)' is deprecated [-Wdeprecated-declarations]
  539 |     index_attribute->setDataType(QAttribute::UnsignedInt);
      |                                                         ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QAttribute:1,
                 from ../../src/camera/pointcloud.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qattribute.h:130:24: note: declared here
  130 |     QT_DEPRECATED void setDataType(VertexBaseType type);
      |                        ^~~~~~~~~~~
../../src/camera/pointcloud.cpp:540:35: warning: 'void Qt3DRender::QAttribute::setDataSize(uint)' is deprecated [-Wdeprecated-declarations]
  540 |     index_attribute->setDataSize(1);
      |                                   ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QAttribute:1,
                 from ../../src/camera/pointcloud.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qattribute.h:131:24: note: declared here
  131 |     QT_DEPRECATED void setDataSize(uint size);
      |                        ^~~~~~~~~~~
../../src/camera/pointcloud.cpp: In member function 'void PointCloud::setOptionsAttribute()':
../../src/camera/pointcloud.cpp:554:51: warning: 'void Qt3DRender::QAttribute::setDataType(Qt3DRender::QAttribute::VertexBaseType)' is deprecated [-Wdeprecated-declarations]
  554 |     options_attribute->setDataType(QAttribute::Int);
      |                                                   ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QAttribute:1,
                 from ../../src/camera/pointcloud.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qattribute.h:130:24: note: declared here
  130 |     QT_DEPRECATED void setDataType(VertexBaseType type);
      |                        ^~~~~~~~~~~
../../src/camera/pointcloud.cpp:555:37: warning: 'void Qt3DRender::QAttribute::setDataSize(uint)' is deprecated [-Wdeprecated-declarations]
  555 |     options_attribute->setDataSize(1);
      |                                     ^
In file included from /usr/include/x86_64-linux-gnu/qt5/Qt3DRender/QAttribute:1,
                 from ../../src/camera/pointcloud.cpp:18:
/usr/include/x86_64-linux-gnu/qt5/Qt3DRender/qattribute.h:131:24: note: declared here
  131 |     QT_DEPRECATED void setDataSize(uint size);
      |                        ^~~~~~~~~~~
[134/135] Building CXX object CMakeFiles/handy3dscanner.dir/src/gltf2/sceneentityparser.cpp.o
ninja: build stopped: subcommand failed.
`

If you can help me.

**Comment by rabits** [comment]
Hi @pagetronic , could you please describe the environment you using for compilation:
* version you trying to compile - master or some another one?
* Qt version - I see you using some modern Qt version, and H3DS is not support them
* some other useful information...

Most probably you are not following the [Build](https://github.com/state-of-the-art/Handy3DScanner#build) procedure, so I think it's a good place to start.

**Comment by rabits** [comment]
So I suppose the build process was not followed (never unsupported version of Qt was used) and now it's working as expected. If not - please reopen the ticket.
