### ISSUE TITLE
[BUG] Crashing on Android 14

### ISSUE THREAD

**Issue by parkerlreed** [state-of-the-art/Handy3DScanner#85]
### Issue description:
Window is created and instantly closes when trying to run on Android 14 on a Samsung S8 Plus tablet

### Environment:
* **Application version**: master
* **Device**: Samsung Tab S8 Plus
* **OS**: Android 14
* **Camera**: RealSense D435
* **Camera firmware**: Unknown

### Steps to reproduce:
1. Compiled Handy from source using Docker container (I had to manually update CMake as draco requires 3.12 or newer now)
2. Installed resulting APK to device
3. Tap on application

### Expected behavior
Application running

### Additional context
Tombstone from crash

[tomb.zip](https://github.com/user-attachments/files/16323162/tomb.zip)

**Comment by parkerlreed** [comment]
After some more testing and finding a random APK online... It's running fine on Android 14. 

So maybe the build breaks with newer CMake? The docker container provided only supplies 3.10 while 3.12 is a hard requirement now.

Could we maybe get an APK published to releases as to not trust a random download online? (Considering the Play Store link is long dead)

**Comment by rabits** [comment]
Hi @parkerlreed , yeah the project is no longer maintained, so I archived it. Sorry to hear you have issues with building - I will upload the latest release binary to the releases page.

**Comment by rabits** [comment]
Ok, just uploaded versions 0.5.2 and 0.5.3 from google play right into releases. In theory if you will build on the older versions of NDK/SDK with all the olde dependencies - should work fine.
